<?php

namespace AprendizajeBundle\Repository;

/**
 * ConversacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversacionRepository extends \Doctrine\ORM\EntityRepository
{
}
