<?php

namespace AprendizajeBundle\Repository;

/**
 * UsuarioVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
